/*
 * signal_store.h - Persisted RF signals and button matching.
 *
 * A "signal" is one recorded or synthesized waveform. A "button" is not a
 * separate entity: it is simply a stored signal that a source node references.
 * Collapsing the two removes a whole class of bookkeeping (orphaned buttons,
 * signals belonging to two buttons) at no cost to the user's mental model —
 * you register a button, and what gets stored is its signal.
 *
 * STORAGE SPLIT. Each signal's full pulse frame is ~1 KB, so holding 32 of them
 * in RAM would cost 35 KB for data that is almost never read. Instead every
 * frame lives in its own NVS blob, loaded on demand, while a compact metadata
 * index (~80 bytes each) stays resident. Matching only needs the metadata, so
 * the hot path never touches flash.
 *
 * MATCHING. An incoming burst is matched by decoded identity when a decoder
 * claimed it (protocol + id + button is far stronger evidence than timing), and
 * otherwise by fingerprint over the normalized timing structure. Raw durations
 * are never compared directly — cheap transmitters drift several percent between
 * presses and as their batteries age.
 *
 * WHERE SIGNALS COME FROM, AND WHAT IS NOT HERE ANY MORE. This module used to
 * own a second entry point called learn mode: an armed window during which an
 * unrecognized burst could be offered to the user as a candidate — but only if
 * it repeated at least twice AND normalized to at least 65 % confidence. Both
 * thresholds were measured on EV1527 remotes, which made them a filter on
 * PROTOCOL SHAPE rather than on plausibility. A transmitter that failed either
 * one never became a candidate at all, and the user was told nothing: the screen
 * simply stayed empty. That is the exact opposite of this project's promise that
 * an undecodable signal is still a first-class signal.
 *
 * The gate is gone, along with the mode. Registration now happens through a
 * listening session (rf_raw.h): every frame is kept, repeats are grouped,
 * candidates are RANKED rather than admitted, and a decode raises a candidate up
 * the list instead of deciding whether it exists. What reaches this module is
 * therefore always a deliberate human choice, and db_signals_add_frame() stores
 * it exactly as given.
 *
 * The receiver is, and always was, ALWAYS listening — there is no on-demand
 * receive mode to switch on, because a button you already registered has to ring
 * the instant it is pressed.
 *
 * THREADING CONTRACT — read before calling anything here from a new task.
 *
 * Every function that takes or fills a caller-owned buffer is safe from ANY
 * task: it locks, copies, unlocks (db_signals_get_copy, db_signals_snapshot,
 * db_signals_load_frame, db_signals_match, all mutators).
 *
 * The three POINTER-RETURNING accessors — db_signals_list, db_signals_get,
 * db_signals_find_decoded — hand out interior pointers into the live array,
 * which delete() compacts with element-by-element shifts. Such a pointer is
 * only meaningful on the one task that performs the mutations, where nothing
 * can shift the array between the call and the last dereference. In this
 * firmware that is the HTTP server task, and ONLY that task may use them. The
 * MQTT bridge and the dispatch task run concurrently with HTTP on the other
 * core: from there a live pointer can start describing a DIFFERENT signal
 * mid-read (a press published under the wrong name, the wrong waveform keyed).
 * Those tasks must take snapshots/copies instead.
 */
#ifndef DB_SIGNAL_STORE_H
#define DB_SIGNAL_STORE_H

#include <stdbool.h>
#include <stdint.h>

#include "esp_err.h"
#include "rf_decode.h"
#include "rf_frame.h"
#include "rf_service.h"

#ifdef __cplusplus
extern "C" {
#endif

#define DB_SIGNAL_MAX      32
#define DB_SIGNAL_NAME_MAX 32

typedef enum {
    DB_ORIGIN_CAPTURED = 0,   /* recorded off the air from a real remote */
    DB_ORIGIN_SYNTHESIZED,    /* generated by us, to pair a receiver to */
    DB_ORIGIN_IMPORTED,       /* uploaded via the API */
} db_signal_origin_t;

/* Resident metadata. The pulse frame is NOT here — see the storage split. */
typedef struct {
    uint16_t         id;                 /* 1..N; 0 means "none"/invalid */
    char             name[DB_SIGNAL_NAME_MAX];
    uint8_t          origin;             /* db_signal_origin_t */
    int64_t          created_at;         /* unix seconds, 0 if clock unknown */
    rf_fingerprint_t fingerprint;
    uint16_t         base_us;
    uint8_t          confidence;
    uint16_t         pulse_count;
    /* Decoded identity, when a decoder claimed the frame. */
    bool             decoded_valid;
    char             protocol[RF_PROTOCOL_NAME_MAX];
    uint32_t         decoded_id;
    uint8_t          decoded_button;
    /* Live stats, not persisted. */
    int64_t          last_seen_us;
    uint32_t         seen_count;
} db_signal_meta_t;

esp_err_t db_signals_init(void);

int db_signals_count(void);

/* HTTP TASK ONLY (see the threading contract above): these return pointers
 * into the live array, valid only where no delete can run concurrently. Every
 * other task uses db_signals_get_copy() / db_signals_snapshot() below. */
const db_signal_meta_t *db_signals_list(void);              /* array of count() */
const db_signal_meta_t *db_signals_get(uint16_t id);        /* NULL if absent */

/* Copy one signal's metadata out under the lock. Safe from any task; this is
 * what the MQTT bridge and the dispatch task must use instead of
 * db_signals_get(). ESP_ERR_NOT_FOUND if no such id. */
esp_err_t db_signals_get_copy(uint16_t id, db_signal_meta_t *out);

/* Copy up to `max` metadata records out under the lock and return how many
 * were written. The copy is internally consistent — taken in one critical
 * section, so no record in it can be half one signal and half another — but it
 * is a snapshot: signals may be added or deleted the moment it returns, which
 * is fine for building tables and announcements (the change notification will
 * trigger a rebuild) and exactly why no pointer into the live array is given
 * out. `out` must hold max records; DB_SIGNAL_MAX always suffices. */
int db_signals_snapshot(db_signal_meta_t *out, int max);

/* Store a captured burst. Copies the frame to NVS and adds the metadata.
 *
 * FULLNESS IS TWO DIFFERENT ERRORS, on this and every other add path:
 *   ESP_ERR_NO_MEM                the DB_SIGNAL_MAX slot count is exhausted;
 *   ESP_ERR_NVS_NOT_ENOUGH_SPACE  the NVS partition itself has no room for
 *                                 this frame plus the index rewrite (checked
 *                                 UP FRONT, with headroom reserved so config
 *                                 and graph saves keep working — see store()
 *                                 in signal_store.c). Long raw recordings can
 *                                 hit this well before the slot count does,
 *                                 especially on boxes still running the
 *                                 original 24 KB NVS partition, which an OTA
 *                                 update can never enlarge.
 * Both are cured the same way — delete signals — but the API must be able to
 * say which wall was hit. */
esp_err_t db_signals_add_event(const rf_event_t *ev, const char *name,
                               db_signal_origin_t origin, uint16_t *id_out);

/* Store a synthesized/imported/captured frame directly. This is the one path a
 * registration takes: a listening session hands over the exact waveform the user
 * inspected and tested, and it is stored verbatim. A DB_ORIGIN_CAPTURED frame is
 * additionally reported to db_diag, decoded or not — an unknown protocol being
 * kept successfully is news worth printing. */
esp_err_t db_signals_add_frame(const rf_frame_t *frame, const rf_decoded_t *decoded,
                               const char *name, db_signal_origin_t origin,
                               uint16_t *id_out);

esp_err_t db_signals_load_frame(uint16_t id, rf_frame_t *out);
esp_err_t db_signals_rename(uint16_t id, const char *name);

/* Delete a signal: the index (minus the entry) is committed FIRST, then the
 * frame blob is erased — a power cut between the two leaves an orphaned blob
 * (harmless, swept at the next boot), never a listed signal whose waveform is
 * gone. On a partition too full to rewrite the index the order flips once
 * (frame freed first) so a full store can always be dug out of; init() repairs
 * whatever a badly-timed power cut leaves either way. */
esp_err_t db_signals_delete(uint16_t id);

/* Match an incoming burst against the store. Returns the signal id, or 0.
 * Also updates last_seen_us / seen_count on a hit. */
uint16_t db_signals_match(const rf_event_t *ev);

/* Find the stored signal that carries a given decoded identity, or NULL.
 * HTTP TASK ONLY — returns a pointer into the live array (threading contract
 * above).
 *
 * The key is protocol + address + button — deliberately the SAME key
 * db_signals_match() uses, because "would an incoming burst be ambiguous
 * between these two signals?" is the only question a duplicate check is
 * entitled to ask. Two entries sharing an address but not a button are not
 * ambiguous at all: that is simply a multi-button remote, and the matcher tells
 * them apart perfectly. */
const db_signal_meta_t *db_signals_find_decoded(const char *protocol,
                                                uint32_t id, uint8_t button);

/* ---- virtual signal creation ----
 * Generates an EV1527 word and stores it. This is how a user pairs one of THEIR
 * receivers to this box: create a virtual signal, put the receiver into learning
 * mode, and transmit it. If id20 is 0 a random address is drawn.
 *
 * `allow_duplicate` false refuses an address+button that a stored signal already
 * carries, returning ESP_ERR_INVALID_STATE — such a pair makes db_signals_match()
 * ambiguous, and whichever entry sits earlier in the store wins, silently. True
 * creates it anyway, which is a legitimate thing to want: re-creating a captured
 * code as a synthesized one is how you check that the box can *generate* a code
 * it can only currently *replay*. Callers that expose this to a human should
 * look the conflict up with db_signals_find_decoded() first so they can name it.
 */
esp_err_t db_signals_create_virtual(const char *name, uint32_t id20, uint8_t button4,
                                    uint16_t base_us, bool allow_duplicate,
                                    uint16_t *id_out);

#ifdef DB_HOSTTEST
/* Host tests only (host-test/Makefile defines DB_HOSTTEST): forget the
 * resident state so db_signals_init() can be run again, simulating a reboot
 * against whatever the fake flash holds. Does not exist in a device build. */
void db_signals_hosttest_reset(void);
#endif

#ifdef __cplusplus
}
#endif

#endif /* DB_SIGNAL_STORE_H */
