/*
 * signal_store.h - Persisted RF signals, button matching, and learn mode.
 *
 * A "signal" is one recorded or synthesized waveform. A "button" is not a
 * separate entity: it is simply a stored signal that a source node references.
 * Collapsing the two removes a whole class of bookkeeping (orphaned buttons,
 * signals belonging to two buttons) at no cost to the user's mental model —
 * you learn a button, and what gets stored is its signal.
 *
 * STORAGE SPLIT. Each signal's full pulse frame is ~1 KB, so holding 32 of them
 * in RAM would cost 35 KB for data that is almost never read. Instead every
 * frame lives in its own NVS blob, loaded on demand, while a compact metadata
 * index (~80 bytes each) stays resident. Matching only needs the metadata, so
 * the hot path never touches flash.
 *
 * MATCHING. An incoming burst is matched by decoded identity when a decoder
 * claimed it (protocol + id + button is far stronger evidence than timing), and
 * otherwise by fingerprint over the normalized timing structure. Raw durations
 * are never compared directly — cheap transmitters drift several percent between
 * presses and as their batteries age.
 *
 * LEARN MODE. The receiver is ALWAYS listening; learn mode only changes what
 * happens to an *unrecognized* burst — normally dropped, but while armed it is
 * offered as a candidate for registration. It is time-boxed so a box never sits
 * armed indefinitely. Admission criteria are deliberately strict (see
 * DB_LEARN_MIN_*): on a live bench the band's AGC noise scored 24-28%
 * confidence and real presses 67-92%, so a floor at 65 sits in an empty gap.
 */
#ifndef DB_SIGNAL_STORE_H
#define DB_SIGNAL_STORE_H

#include <stdbool.h>
#include <stdint.h>

#include "esp_err.h"
#include "rf_decode.h"
#include "rf_frame.h"
#include "rf_service.h"

#ifdef __cplusplus
extern "C" {
#endif

#define DB_SIGNAL_MAX      32
#define DB_SIGNAL_NAME_MAX 32

/* Learn-mode admission thresholds — see the file header for the bench data. */
#define DB_LEARN_MIN_CONFIDENCE 65
#define DB_LEARN_MIN_REPEATS    2
#define DB_LEARN_DEFAULT_SECS   60

typedef enum {
    DB_ORIGIN_CAPTURED = 0,   /* learned from a real remote */
    DB_ORIGIN_SYNTHESIZED,    /* generated by us, to pair a receiver to */
    DB_ORIGIN_IMPORTED,       /* uploaded via the API */
} db_signal_origin_t;

/* Resident metadata. The pulse frame is NOT here — see the storage split. */
typedef struct {
    uint16_t         id;                 /* 1..N; 0 means "none"/invalid */
    char             name[DB_SIGNAL_NAME_MAX];
    uint8_t          origin;             /* db_signal_origin_t */
    int64_t          created_at;         /* unix seconds, 0 if clock unknown */
    rf_fingerprint_t fingerprint;
    uint16_t         base_us;
    uint8_t          confidence;
    uint16_t         pulse_count;
    /* Decoded identity, when a decoder claimed the frame. */
    bool             decoded_valid;
    char             protocol[RF_PROTOCOL_NAME_MAX];
    uint32_t         decoded_id;
    uint8_t          decoded_button;
    /* Live stats, not persisted. */
    int64_t          last_seen_us;
    uint32_t         seen_count;
} db_signal_meta_t;

esp_err_t db_signals_init(void);

int                     db_signals_count(void);
const db_signal_meta_t *db_signals_list(void);              /* array of count() */
const db_signal_meta_t *db_signals_get(uint16_t id);        /* NULL if absent */

/* Store a captured burst. Copies the frame to NVS and adds the metadata. */
esp_err_t db_signals_add_event(const rf_event_t *ev, const char *name,
                               db_signal_origin_t origin, uint16_t *id_out);

/* Store a synthesized/imported frame directly. */
esp_err_t db_signals_add_frame(const rf_frame_t *frame, const rf_decoded_t *decoded,
                               const char *name, db_signal_origin_t origin,
                               uint16_t *id_out);

esp_err_t db_signals_load_frame(uint16_t id, rf_frame_t *out);
esp_err_t db_signals_rename(uint16_t id, const char *name);
esp_err_t db_signals_delete(uint16_t id);

/* Match an incoming burst against the store. Returns the signal id, or 0.
 * Also updates last_seen_us / seen_count on a hit. */
uint16_t db_signals_match(const rf_event_t *ev);

/* ---- learn mode ---- */
void db_signals_learn_arm(uint32_t timeout_secs);   /* 0 => DB_LEARN_DEFAULT_SECS */
void db_signals_learn_cancel(void);
bool db_signals_learn_active(uint32_t *remaining_secs);

/* Offer an unmatched burst to learn mode. Returns true if it was accepted as the
 * pending candidate (i.e. armed AND it met the admission criteria). Called from
 * the RF event path; cheap and safe when not armed. */
bool db_signals_learn_offer(const rf_event_t *ev);

/* The pending candidate, if any, for the UI to show before confirming. */
bool db_signals_learn_candidate(db_signal_meta_t *out);

/* As above, plus the reception quality of the burst that produced the candidate.
 * Split out as a separate call rather than widening db_signal_meta_t because
 * RSSI and repeat count describe ONE reception, not the stored signal — a signal
 * heard again next week has different values, so they do not belong in the
 * persisted metadata. The UI needs them precisely because they are what tells a
 * user whether the candidate is worth accepting. Either out-pointer may be NULL. */
bool db_signals_learn_candidate_info(db_signal_meta_t *meta,
                                     int16_t *rssi_dbm, uint8_t *repeats);

/* Commit the pending candidate as a stored signal, and disarm. */
esp_err_t db_signals_learn_accept(const char *name, uint16_t *id_out);

/* ---- virtual signal creation ----
 * Generates a fresh EV1527 address and stores it. This is how a user pairs one
 * of THEIR receivers to this box: create a virtual signal, put the receiver into
 * learning mode, and transmit it. If id20 is 0 a random address is drawn. */
esp_err_t db_signals_create_virtual(const char *name, uint32_t id20, uint8_t button4,
                                    uint16_t base_us, uint16_t *id_out);

#ifdef __cplusplus
}
#endif

#endif /* DB_SIGNAL_STORE_H */
